<?php

/**
 * @file
 * Enables tooltip sitewide.
 */

define('TOOLTIP_ANYWHERE_TOOLTIPSTER_PATH', 'sites/all/libraries/tooltipster');

/**
 * Initialization of tooltip_anywhere (on each page).
 */
function tooltip_anywhere_page_build(&$page) {
  $scripts = "(function($) {
    $(document).ready(function() {
      $('.tooltip').tooltipster();
    });
  })(jQuery);";
  drupal_add_js($scripts, 'inline');
  // Attach tooltip anyhwhere module js file.
  drupal_add_js(drupal_get_path('module', 'tooltip_anywhere') . '/js/tooltip_anywhere.js');
  // Attach tooltipster files.
  drupal_add_css(TOOLTIP_ANYWHERE_TOOLTIPSTER_PATH . '/tooltipster.css');
  drupal_add_js(TOOLTIP_ANYWHERE_TOOLTIPSTER_PATH . '/jquery.tooltipster.min.js');
}

/**
 * Get tool tip by ajax or on page load; works in each case.
 */
function tooltip_anywhere_initialize($selector, $type = NULL, $content = NULL, $position = NULL, $others = NULL) {
  if (empty($position)) {
    $position = "bottom";
  }
  if (empty($content)) {
    $content = t("No content available.");
  }
  if (!is_array($others)) {
    $others = array('theme' => 'tooltipster-default');
  }
  if ($type === "id") {
    $selector = "#" . $selector;
  }
  elseif ($type === "class") {
    $selector = "." . $selector;
  }
  $data = array();
  $data['type'][] = $type;
  $data['selector'][] = $selector;
  $data['position'][] = $position;
  $data['properties'][] = $others;
  $data['content'][] = $content;
  drupal_add_js(array('vars' => $data), 'setting');
}
